services:
  real-estate-api:
    container_name: real-estate-api
    "build": {
      "dockerfile": "Dockerfile"
    }
    ports:
      - "9002:9002"  # for PHP-FPM
      - "44857:44857"  # for Xdebug
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=44857
    volumes:
      - ./api:/var/www/html/
    restart: unless-stopped
    command:
      sh -c "composer install &&
      php artisan serve --host=0.0.0.0 --port=9002"
    networks:
        - real-estate-network
networks:
  real-estate-network:
    driver: bridge